#!/bin/bash
# Suricata Rule Builder - Installation Script
# This script helps set up the application for production use

set -e  # Exit on error

echo "🛡️  Suricata Rule Builder - Installation"
echo "========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo "⚠️  Please do not run this script as root"
    echo "It will ask for sudo password when needed"
    exit 1
fi

# Check Python version
echo "Checking Python version..."
PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
REQUIRED_VERSION="3.8"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo "❌ Python $REQUIRED_VERSION or higher is required"
    echo "Current version: $PYTHON_VERSION"
    exit 1
fi

echo "✓ Python $PYTHON_VERSION found"
echo ""

# Ask installation type
echo "Choose installation type:"
echo "1) Development (current directory)"
echo "2) Production (install to /opt)"
echo ""
read -p "Enter choice [1-2]: " INSTALL_TYPE

if [ "$INSTALL_TYPE" == "2" ]; then
    INSTALL_DIR="/opt/suricata-rule-builder"
    echo ""
    echo "Installing to: $INSTALL_DIR"

    # Create installation directory
    sudo mkdir -p "$INSTALL_DIR"
    sudo chown $USER:$USER "$INSTALL_DIR"

    # Copy files
    echo "Copying files..."
    cp -r ./* "$INSTALL_DIR/"
    cd "$INSTALL_DIR"
else
    INSTALL_DIR=$(pwd)
    echo ""
    echo "Installing in: $INSTALL_DIR"
fi

echo ""
echo "📦 Setting up Python virtual environment..."
python3 -m venv venv

echo "🔄 Activating virtual environment..."
source venv/bin/activate

echo "📥 Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo ""
echo "📝 Creating rules file..."

# Ask for rules file location
read -p "Use /etc/suricata/rules/custom.rules? [Y/n]: " USE_SYSTEM_RULES

if [ "$USE_SYSTEM_RULES" != "n" ] && [ "$USE_SYSTEM_RULES" != "N" ]; then
    RULES_FILE="/etc/suricata/rules/custom.rules"

    # Create directory if needed
    if [ ! -d "/etc/suricata/rules" ]; then
        echo "Creating /etc/suricata/rules directory..."
        sudo mkdir -p /etc/suricata/rules
    fi

    # Create rules file if needed
    if [ ! -f "$RULES_FILE" ]; then
        echo "Creating $RULES_FILE..."
        sudo tee "$RULES_FILE" > /dev/null << 'EOF'
# Suricata Custom Rules
# Generated by Suricata Rule Builder

EOF
        sudo chmod 644 "$RULES_FILE"
    fi

    # Ensure we have write permissions
    sudo chown $USER:$USER "$RULES_FILE" 2>/dev/null || true
else
    RULES_FILE="$INSTALL_DIR/custom.rules"
    if [ ! -f "$RULES_FILE" ]; then
        cat > "$RULES_FILE" << 'EOF'
# Suricata Custom Rules
# Generated by Suricata Rule Builder

EOF
    fi
fi

echo "✓ Rules file: $RULES_FILE"

# Configure sudo for Suricata reload
echo ""
read -p "Configure sudo for Suricata service reload? [Y/n]: " SETUP_SUDO

if [ "$SETUP_SUDO" != "n" ] && [ "$SETUP_SUDO" != "N" ]; then
    echo "Adding sudo configuration..."

    SUDOERS_FILE="/etc/sudoers.d/suricata-builder"

    sudo tee "$SUDOERS_FILE" > /dev/null << EOF
# Suricata Rule Builder - Allow service reload without password
$USER ALL=(ALL) NOPASSWD: /bin/systemctl reload suricata
$USER ALL=(ALL) NOPASSWD: /usr/sbin/service suricata reload
$USER ALL=(ALL) NOPASSWD: /usr/bin/killall -USR2 suricata
EOF

    sudo chmod 440 "$SUDOERS_FILE"
    echo "✓ Sudo configuration added"
fi

# Setup systemd service for production
if [ "$INSTALL_TYPE" == "2" ]; then
    echo ""
    read -p "Install systemd service? [Y/n]: " INSTALL_SERVICE

    if [ "$INSTALL_SERVICE" != "n" ] && [ "$INSTALL_SERVICE" != "N" ]; then
        echo "Installing systemd service..."

        # Update service file paths
        sed -i "s|/opt/suricata-rule-builder|$INSTALL_DIR|g" suricata-builder.service

        # Create log directory
        sudo mkdir -p /var/log/suricata-builder
        sudo chown $USER:$USER /var/log/suricata-builder

        # Install service
        sudo cp suricata-builder.service /etc/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl enable suricata-builder

        echo "✓ Systemd service installed"
        echo ""
        echo "Start the service with: sudo systemctl start suricata-builder"
        echo "Check status with: sudo systemctl status suricata-builder"
    fi
fi

echo ""
echo "============================================"
echo "✅ Installation Complete!"
echo "============================================"
echo ""

if [ "$INSTALL_TYPE" == "2" ]; then
    echo "The Suricata Rule Builder has been installed to: $INSTALL_DIR"
    echo ""
    echo "To start the service:"
    echo "  sudo systemctl start suricata-builder"
    echo ""
    echo "To check status:"
    echo "  sudo systemctl status suricata-builder"
    echo ""
    echo "Access the dashboard at: http://localhost:5500"
else
    echo "To start the development server:"
    echo "  cd $INSTALL_DIR"
    echo "  ./start.sh"
    echo ""
    echo "Or manually:"
    echo "  source venv/bin/activate"
    echo "  python app.py"
    echo ""
    echo "Access the dashboard at: http://localhost:5500"
fi

echo ""
echo "For more information, see README.md"
echo ""
