#!/bin/bash
# Suricata Rule Builder - Startup Script

echo "🛡️  Suricata Rule Builder Dashboard"
echo "===================================="
echo ""

# Check if Python 3 is installed
if ! command -v python3 &> /dev/null; then
    echo "❌ Error: Python 3 is not installed"
    echo "Please install Python 3.8 or higher"
    exit 1
fi

echo "✓ Python 3 found: $(python3 --version)"

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo ""
    echo "📦 Creating virtual environment..."
    python3 -m venv venv

    if [ $? -ne 0 ]; then
        echo "❌ Failed to create virtual environment"
        exit 1
    fi
    echo "✓ Virtual environment created"
fi

# Activate virtual environment
echo ""
echo "🔄 Activating virtual environment..."
source venv/bin/activate

# Check if dependencies are installed
if [ ! -f "venv/installed.flag" ]; then
    echo ""
    echo "📥 Installing dependencies..."
    pip install -r requirements.txt

    if [ $? -ne 0 ]; then
        echo "❌ Failed to install dependencies"
        exit 1
    fi

    touch venv/installed.flag
    echo "✓ Dependencies installed"
else
    echo "✓ Dependencies already installed"
fi

# Create custom.rules if it doesn't exist
if [ ! -f "custom.rules" ]; then
    echo ""
    echo "📝 Creating custom.rules file..."
    cat > custom.rules << 'EOF'
# Suricata Custom Rules
# Generated by Suricata Rule Builder
#
# Custom rules should use SID >= 1000000 to avoid conflicts
#
# Example rules:
# alert tcp any any -> any 80 (msg:"HTTP GET Request"; content:"GET"; http_method; sid:1000001; rev:1;)
# alert dns any any -> any any (msg:"DNS Query"; dns.query; content:"example.com"; sid:1000002; rev:1;)

EOF
    echo "✓ custom.rules created"
fi

echo ""
echo "🚀 Starting Suricata Rule Builder Dashboard..."
echo ""
echo "================================================"
echo "  Access the dashboard at: http://localhost:5500"
echo "  Press Ctrl+C to stop the server"
echo "================================================"
echo ""

# Start the Flask application
python app.py
